name: model-training
on: [push]
jobs:
  run:
    runs-on: Windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Train model
        run: |
          pip install -r requirements.txt
          python model_main.py
